FROM node:14.15.4 AS build
RUN apt update && \
    apt install -y apt-utils libx11-xcb1 libxtst6 libnss3 libxss1 libasound2 libatk-bridge2.0-0 libgtk-3-0 default-jre
RUN npm i -g @angular/cli@8
WORKDIR /hub

COPY ./client/package.json .
RUN npm i

COPY ./client/.browserslistrc ./client/tslint.json ./client/tsconfig.app.json ./client/tsconfig.json ./client/angular.json ./
COPY ./client/src/ ./src/
RUN ng build --prod

COPY ./client/tsconfig.spec.json ./client/karma.conf.js ./
COPY ./client/e2e/ ./e2e/
RUN npm run test
# RUN npm run e2e

###########################################################################

FROM nginx AS run
COPY --from=build /hub/dist/* /usr/share/nginx/html/
COPY ./client/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
