FROM node:14.15.4 AS client
RUN npm i -g @angular/cli@8
WORKDIR /hub

COPY ./package.json .
RUN npm i

COPY ./.browserslistrc ./tslint.json ./tsconfig.app.json ./tsconfig.json ./angular.json ./
COPY ./src/ ./src/
RUN ng build --prod

COPY ./tsconfig.spec.json ./karma.conf.js ./
COPY ./e2e/ ./e2e/
# RUN npm run test
# RUN npm run e2e

EXPOSE 80
CMD ng serve --host 0.0.0.0 --port 80

#################################################

FROM node:14.15.4 AS server
RUN npm i -g json-server
WORKDIR /hub

COPY ./src/mocks/ ./src/mocks/

EXPOSE 80
CMD json-server src/mocks/db.json --host 0.0.0.0 --port 80
