version: "3.8"

services:
  client:
    container_name: "client"
    build:
      context: .
      dockerfile: ./client/dockerfile
      target: run
    depends_on:
      - server
    ports:
      - 4200:80
    networks:
      - client
    restart: always

  server:
    container_name: "server"
    build:
      context: .
      dockerfile: ./server/dockerfile
    networks:
      - client
    volumes:
      - ./server/mocks/db.json:/hub/mocks/db.json
    restart: always

networks:
  client:
    driver: bridge
