version: '3.8'

services:

    client:
        container_name: 'client'
        build:
            context: .
            dockerfile: ./dockerfile.client
            target: run
        depends_on:
            - server
        ports:
            - 4200:80
        restart: always

    server:
        container_name: 'server'
        build:
            context: .
            dockerfile: ./dockerfile.server
            target: server
        volumes:
            - ./mocks/db.json:/hub/mocks/db.json
        restart: always
